### ISSUE TITLE
The format of the files under the topology folder 

### ISSUE THREAD

**Issue by weiqingcai** [VolSec/chaos#1]
Hi  #@jaredthecoder, I am having some confusion when I am trying to use your system. The readme document says that these two files are needed under the topology folder. 
> This folder should have several files in it:
>   - An IP mapping from CAIDA
>   - The latest inferred topology from CAIDA

But I don't know what format these two files should have.Can you provide two samples?Thank you very much

**Comment by jaredthecoder** [comment]
I will add these two files for the most recent CAIDA topologies. You can also get them at CAIDA.org.

**Comment by jaredthecoder** [comment]
Updated that folder!
